




enable_csi: True



ds_configs:
  preprocess:
    path: "/mnt/ssd/csi_pipeline/config/ds_config/config_preprocess.txt"
    network-input-shape: "1;3;480;480"
    draw-roi: "0"
    #roi-params-src-0: "390;260;960;960"
    roi-params-src-0: "230;100;960;960"
    #roi-params-src-0: "175;5;1075;1075"
    #roi-params-src-0: "0;0;1920;1080"
  inference:
    path: "/mnt/ssd/csi_pipeline/config/ds_config/infer_config.txt"
    model-engine-file: "/mnt/ssd/model_repository/nozzlenet-v2/V253/ssd_resnet18_epoch_060-nozzlenet-batch-size-1.plan"
    labelfile-path: "/mnt/ssd/csi_pipeline/models/nozzlenet-v2/V250/labels.txt"
    infer-dims: "3;480;480"
    input-tensor-from-meta: "0"
  metamux:
    path: "/mnt/ssd/csi_pipeline/config/ds_config/config_metamux.txt"
  tracker:
    path: "/mnt/ssd/workspace/ganindu_ws/scripts/nvDCF_tracker_config.yml"



source_override_parameters:
  source_1:
    id: 0
    name: "front"
    override: False
    codec: "h264"
    file_path: "./videos/fiels_testing/front_trimmed.mp4"
  source_2:
    id: 1
    name: "rear"
    override: False
    codec: "h264"
    file_path: "./videos/rear_view.mp4"
  source_3:
    id: 2
    name: "primary_nozzle"
    type: "file"
    override: False
    codec: "h264"
    file_path: "videos/nozzle_grav.mp4"
  source_4:
    name: "secondary_nozzle"
    id: 3
    override: False



